### ISSUE TITLE
Node engine uses fixed version 8

### ISSUE THREAD

**Issue by michaelbaur** [y1j2x34/gulp-file-checksum#1]
I suppose it would work fine with node 10 and 12, too. Maybe you can change it to
```
  "engines": {
    "node": ">=8.0.0"
  },
```

**Comment by diroussel** [comment]
I have this problem too.  Is there a reason why this plugin doesn't work with higher node versions?

**Comment by y1j2x34** [comment]
Fixed in version 2.0.2
